language: C
sudo: false
matrix:
  include:
    - os: linux
      compiler: gcc
      env: CLANG_BUILD=OFF
    - os: linux
      compiler: clang
      env: CLANG_BUILD=ON
script:
  # Print all environment variables to aid in CI development
  - printenv
  # Print version and available CMake generators to aid in CI development
  - cmake --version
  - cmake --help

  # Perform out-of-source build(CMake backend generation, build, and test)
  # Test build without optimizations
  - rm -r build/*
  - cd build
  - cmake .. -DCERAII_TEST_BUILD=ON -DCERAII_CLANG_BUILD=${CLANG_BUILD} -CERAII_PERF_OPTIMIZED_BUILD=OFF
  - cmake --build . --target all 
  - ls
  - ./test_basic
  - ./test_multithread
  # Test build with optimizations
  - rm -r build/*
  - cd build
  - cmake .. -DCERAII_TEST_BUILD=ON -DCERAII_CLANG_BUILD=${CLANG_BUILD} -CERAII_PERF_OPTIMIZED_BUILD=ON
  - cmake --build . --target all 
  - ls
  - ./test_basic
  - ./test_multithread
  # Production build without optimizations
  - cd ..  
  - rm -r build/*
  - cd build
  - cmake .. -DCERAII_TEST_BUILD=OFF -DCERAII_CLANG_BUILD=${CLANG_BUILD} -CERAII_PERF_OPTIMIZED_BUILD=OFF
  - cmake --build . --target all 
  - ls
  - ./test_basic
  - ./test_multithread
  # Production build with optimizations
  - cd ..  
  - rm -r build/*
  - cd build
  - cmake .. -DCERAII_TEST_BUILD=OFF -DCERAII_CLANG_BUILD=${CLANG_BUILD} -CERAII_PERF_OPTIMIZED_BUILD=ON
  - cmake --build . --target all 
  - ls
  - ./test_basic
  - ./test_multithread
