language: C
sudo: false
matrix:
  include:
    - os: linux
      compiler: gcc
      env: CLANG_BUILD=OFF
    - os: linux
      compiler: clang
      env: CLANG_BUILD=ON
script:
  # Print all environment variables to aid in CI development
  - printenv
  # Print version and available CMake generators to aid in CI development
  - cmake --version
  - cmake --help
  # Perform out-of-source build
  - cd build
  # Perform CMake backend generation, build, and test (CERAII test build)
  - cmake .. -DCERAII_TEST_BUILD=ON -DCERAII_CLANG_BUILD=${CLANG_BUILD}
  - cmake --build . --target all 
  - ls
  - ./test_basic
  - ./test_multithread
  # Perform CMake backend generation, build, and test (CERAII production build)
  - cd ..  
  - rm -r build/*
  - cd build
  - cmake .. -DCERAII_TEST_BUILD=OFF -DCERAII_CLANG_BUILD=${CLANG_BUILD}
  - cmake --build . --target all 
  - ls
  - ./test_basic
  - ./test_multithread
