language: C
sudo: false
matrix:
  include:
    - os: linux
      compiler: gcc
      env: 
        - COVERAGE=ON
        - BUILD_TYPE=Debug
      before_script:
        - pip install --user cpp-coveralls
      after_success:
        - coveralls --build-root build --include src --include tests  --gcov-options '\-lp'
    - os: linux
      compiler: gcc
      env: 
        - BUILD_TYPE=Release

    - os: linux
      compiler: clang
      env: 
        - BUILD_TYPE=Release
    - os: linux
      compiler: clang
      env: 
        - BUILD_TYPE=Debug


script:
  # Print general inforamtion
  - printenv
  - cmake --version
  - cmake --help

  # Basic build
  - cd build
  - cmake .. -DCERAII_TEST_BUILD=ON -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - cmake --build . --target all 
  - ls
  - ./test_basic
  - ./test_multithread

  # Build with sanitizers
  - cd ..  
  - rm -r build/*
  - cd build
  - cmake .. -DCERAII_TEST_BUILD=OFF -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - cmake --build . --target all 
  - ls
  - ./test_basic
  - ./test_multithread

  # Check code coverage
  - if [ ${COVERAGE} == 'ON' ];
    then
    cd ..  ;
    rm -r build/* ;
    cd build ;
    cmake .. -DCERAII_COVERALLS_BUILD=ON -DCERAII_TEST_BUILD=ON -DCMAKE_BUILD_TYPE=Debug ;
    cmake --build . --target all ;
    ls ;
    ./test_basic ;
    ./test_multithread ;
    fi
  - cd ..
